name: timeline
version: '1.18.0'
summary: Timeline
description: |
  Timeline is a cross-platform application for displaying and navigating events on a timeline

grade: stable
confinement: strict

apps:
  timeline:
    plugs: [x11,desktop,unity7,home]
    command: desktop-launch $SNAP/var/opt/timeline/source/timeline.py

parts:
  timeline:
    source: https://downloads.sourceforge.net/project/thetimelineproj/thetimelineproj/$SNAPCRAFT_PROJECT_VERSION/timeline-$SNAPCRAFT_PROJECT_VERSION.zip
    plugin: python
    python-version: python2
    python-packages:
      - humblewx
    stage-packages: [python-wxgtk3.0]
    override-build: |
      snapcraftctl build
      mkdir -p $SNAPCRAFT_PART_INSTALL/var/opt/timeline
      cp -R timeline-$SNAPCRAFT_PROJECT_VERSION/* $SNAPCRAFT_PART_INSTALL/var/opt/timeline
    after: [desktop-gtk2]